///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PMISupervisor.TestCases.VisitWorkReview
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The WorkReview recording.
    /// </summary>
    [TestModule("ed3fab3a-ca0c-4228-9629-391eda1b127d", ModuleType.Recording, 1)]
    public partial class WorkReview : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PMISupervisor.PMISupervisorRepository repository.
        /// </summary>
        public static PMISupervisor.PMISupervisorRepository repo = PMISupervisor.PMISupervisorRepository.Instance;

        static WorkReview instance = new WorkReview();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public WorkReview()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static WorkReview Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='WELCOME') on item 'PMI_Supervisor.Validate_AppStartingScreen'.", repo.PMI_Supervisor.Validate_AppStartingScreenInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.PMI_Supervisor.Validate_AppStartingScreenInfo, "Text", "WELCOME");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PMI_Supervisor.WorkReview_RadioButton' at Center", repo.PMI_Supervisor.WorkReview_RadioButtonInfo, new RecordItemIndex(1));
            repo.PMI_Supervisor.WorkReview_RadioButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PMI_Supervisor.ButtonSubmit' at Center", repo.PMI_Supervisor.ButtonSubmitInfo, new RecordItemIndex(2));
            repo.PMI_Supervisor.ButtonSubmit.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='MERCHANDISERS LIST') on item 'PMI_Supervisor.Validate_MERCHANDISERSLISTScreen'.", repo.PMI_Supervisor.Validate_MERCHANDISERSLISTScreenInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.PMI_Supervisor.Validate_MERCHANDISERSLISTScreenInfo, "Text", "MERCHANDISERS LIST");
            Delay.Milliseconds(0);
            
            UserCode.UserCode.selectMerchandiser();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PMI_Supervisor.Validate_InfoPopUp'.", repo.PMI_Supervisor.Validate_InfoPopUpInfo, new RecordItemIndex(5));
            Validate.Exists(repo.PMI_Supervisor.Validate_InfoPopUpInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PMI_Supervisor.Validation_OKButton' at Center", repo.PMI_Supervisor.Validation_OKButtonInfo, new RecordItemIndex(6));
            repo.PMI_Supervisor.Validation_OKButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='ROUTE LIST') on item 'PMI_Supervisor.Validate_ROUTELISTScreen'.", repo.PMI_Supervisor.Validate_ROUTELISTScreenInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.PMI_Supervisor.Validate_ROUTELISTScreenInfo, "Text", "ROUTE LIST");
            Delay.Milliseconds(0);
            
            UserCode.UserCode.selectRouteDay();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
