///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PMISupervisor.TestCases.VisitNonTKShopOpenOnce
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TPOSMApplication recording.
    /// </summary>
    [TestModule("762a2708-dc88-4ad8-a216-1d88b25610c2", ModuleType.Recording, 1)]
    public partial class TPOSMApplication : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PMISupervisor.PMISupervisorRepository repository.
        /// </summary>
        public static PMISupervisor.PMISupervisorRepository repo = PMISupervisor.PMISupervisorRepository.Instance;

        static TPOSMApplication instance = new TPOSMApplication();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TPOSMApplication()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TPOSMApplication Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Non-TK') on item 'PMI_Supervisor.Validate_NonTKShopScreen'.", repo.PMI_Supervisor.Validate_NonTKShopScreenInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.PMI_Supervisor.Validate_NonTKShopScreenInfo, "Text", "Non-TK");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PMI_Supervisor.TPOSMApplication' at Center", repo.PMI_Supervisor.TPOSMApplicationInfo, new RecordItemIndex(1));
            repo.PMI_Supervisor.TPOSMApplication.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TPOSM Application') on item 'PMI_Supervisor.Validate_TPOSMApplicationScreen'.", repo.PMI_Supervisor.Validate_TPOSMApplicationScreenInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.PMI_Supervisor.Validate_TPOSMApplicationScreenInfo, "Text", "TPOSM Application");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PMI_Supervisor.TPOSMDeployment' at Center", repo.PMI_Supervisor.TPOSMDeploymentInfo, new RecordItemIndex(3));
            repo.PMI_Supervisor.TPOSMDeployment.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TPOSM') on item 'PMI_Supervisor.Validate_TPOSMDeploymentScreen'.", repo.PMI_Supervisor.Validate_TPOSMDeploymentScreenInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.PMI_Supervisor.Validate_TPOSMDeploymentScreenInfo, "Text", "TPOSM");
            Delay.Milliseconds(0);
            
            UserCode.UserCode.visitNonTKAllTPOSM();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'PMI_Supervisor'.", repo.PMI_Supervisor.SelfInfo, new RecordItemIndex(6));
            repo.PMI_Supervisor.Self.PressKeys("{BACK}");
            Delay.Milliseconds(1000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TPOSM Application') on item 'PMI_Supervisor.Validate_TPOSMApplicationScreen'.", repo.PMI_Supervisor.Validate_TPOSMApplicationScreenInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.PMI_Supervisor.Validate_TPOSMApplicationScreenInfo, "Text", "TPOSM Application");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PMI_Supervisor.TPOSM_TakePicture1' at Center", repo.PMI_Supervisor.TPOSM_TakePicture1Info, new RecordItemIndex(8));
            repo.PMI_Supervisor.TPOSM_TakePicture1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PMI_Supervisor.Validate_CameraScreen'.", repo.PMI_Supervisor.Validate_CameraScreenInfo, new RecordItemIndex(9));
            Validate.Exists(repo.PMI_Supervisor.Validate_CameraScreenInfo);
            Delay.Milliseconds(0);
            
            UserCode.UserCode.takePhoto();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PMI_Supervisor.ButtonDone' at Center", repo.PMI_Supervisor.ButtonDoneInfo, new RecordItemIndex(11));
            repo.PMI_Supervisor.ButtonDone.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TPOSM Application') on item 'PMI_Supervisor.Validate_TPOSMApplicationScreen'.", repo.PMI_Supervisor.Validate_TPOSMApplicationScreenInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.PMI_Supervisor.Validate_TPOSMApplicationScreenInfo, "Text", "TPOSM Application");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PMI_Supervisor.TPOSM_TakePicture2' at Center", repo.PMI_Supervisor.TPOSM_TakePicture2Info, new RecordItemIndex(13));
            repo.PMI_Supervisor.TPOSM_TakePicture2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PMI_Supervisor.Validate_CameraScreen'.", repo.PMI_Supervisor.Validate_CameraScreenInfo, new RecordItemIndex(14));
            Validate.Exists(repo.PMI_Supervisor.Validate_CameraScreenInfo);
            Delay.Milliseconds(0);
            
            UserCode.UserCode.takePhoto();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PMI_Supervisor.ButtonDone' at Center", repo.PMI_Supervisor.ButtonDoneInfo, new RecordItemIndex(16));
            repo.PMI_Supervisor.ButtonDone.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TPOSM Application') on item 'PMI_Supervisor.Validate_TPOSMApplicationScreen'.", repo.PMI_Supervisor.Validate_TPOSMApplicationScreenInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.PMI_Supervisor.Validate_TPOSMApplicationScreenInfo, "Text", "TPOSM Application");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'PMI_Supervisor'.", repo.PMI_Supervisor.SelfInfo, new RecordItemIndex(18));
            repo.PMI_Supervisor.Self.PressKeys("{BACK}");
            Delay.Milliseconds(1000);
            
            UserCode.UserCode.loadNonTKAvailabilityCheck();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
