///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PMISupervisor
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PMISupervisorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("dcd8a16c-6d73-4d59-943e-71a35b7b3ac8")]
    public partial class PMISupervisorRepository : RepoGenBaseFolder
    {
        static PMISupervisorRepository instance = new PMISupervisorRepository();
        PMISupervisorRepositoryFolders.PMI_SupervisorAppFolder _pmi_supervisor;

        /// <summary>
        /// Gets the singleton class instance representing the PMISupervisorRepository element repository.
        /// </summary>
        [RepositoryFolder("dcd8a16c-6d73-4d59-943e-71a35b7b3ac8")]
        public static PMISupervisorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PMISupervisorRepository() 
            : base("PMISupervisorRepository", "/", null, 0, false, "dcd8a16c-6d73-4d59-943e-71a35b7b3ac8", ".\\RepositoryImages\\PMISupervisorRepositorydcd8a16c.rximgres")
        {
            _pmi_supervisor = new PMISupervisorRepositoryFolders.PMI_SupervisorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("dcd8a16c-6d73-4d59-943e-71a35b7b3ac8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PMI_Supervisor folder.
        /// </summary>
        [RepositoryFolder("fd56243c-ade9-476f-af68-74733305a57b")]
        public virtual PMISupervisorRepositoryFolders.PMI_SupervisorAppFolder PMI_Supervisor
        {
            get { return _pmi_supervisor; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class PMISupervisorRepositoryFolders
    {
        /// <summary>
        /// The PMI_SupervisorAppFolder folder.
        /// </summary>
        [RepositoryFolder("fd56243c-ade9-476f-af68-74733305a57b")]
        public partial class PMI_SupervisorAppFolder : RepoGenBaseFolder
        {
            PMISupervisorRepositoryFolders.ListFolder _list;
            PMISupervisorRepositoryFolders.List1Folder _list1;
            RepoItemInfo _validate_appstartingscreenInfo;
            RepoItemInfo _workreview_radiobuttonInfo;
            RepoItemInfo _workwith_radiobuttonInfo;
            RepoItemInfo _buttonsubmitInfo;
            RepoItemInfo _validation_okbuttonInfo;
            RepoItemInfo _attendance_buttonInfo;
            RepoItemInfo _validate_attendancescreenInfo;
            RepoItemInfo _merchandisers_attendancelistInfo;
            RepoItemInfo _validate_merchandiserslistscreenInfo;
            RepoItemInfo _merchandisers_listInfo;
            RepoItemInfo _validate_routelistscreenInfo;
            RepoItemInfo _route_listInfo;
            ShopsList_validationInfoClass _shopslist_validationInfo;
            RepoItemInfo _validate_shopslistscreenInfo;
            RepoItemInfo _shops_listInfo;
            RepoItemInfo _validate_infopopupInfo;
            RepoItemInfo _validate_shopdetailsformInfo;
            RepoItemInfo _shopdetailsInfo;
            RepoItemInfo _validate_proceedshopformInfo;
            RepoItemInfo _proceedbuttonInfo;
            RepoItemInfo _validate_tradetrackerscreenInfo;
            RepoItemInfo _checkinbuttonInfo;
            RepoItemInfo _shopremarks_listInfo;
            RepoItemInfo _userlocationisincorrectInfo;
            RepoItemInfo _shopopenInfo;
            RepoItemInfo _validate_camerascreenInfo;
            RepoItemInfo _takephotoInfo;
            RepoItemInfo _buttondoneInfo;
            RepoItemInfo _yesbuttonInfo;
            RepoItemInfo _nobuttonInfo;
            RepoItemInfo _validate_nontkshopscreenInfo;
            RepoItemInfo _tposmapplicationInfo;
            RepoItemInfo _validate_tposmapplicationscreenInfo;
            RepoItemInfo _tposmdeploymentInfo;
            RepoItemInfo _validate_tposmdeploymentscreenInfo;
            RepoItemInfo _tposm_listInfo;
            RepoItemInfo _validate_tposmscreenInfo;
            RepoItemInfo _tposm1_yesInfo;
            RepoItemInfo _tposm_noInfo;
            RepoItemInfo _tposm2_yesInfo;
            RepoItemInfo _validate_tposmquantitypopupInfo;
            RepoItemInfo _tposmquantity_edittextfieldInfo;
            RepoItemInfo _tposmquantity_okbuttonInfo;
            RepoItemInfo _tposm_takepicture1Info;
            RepoItemInfo _tposm_takepicture2Info;
            RepoItemInfo _availabilitycheckInfo;
            RepoItemInfo _validate_availabilitycheckscreenInfo;
            RepoItemInfo _availabilitycheck_listInfo;
            RepoItemInfo _nontkmodules_listInfo;

            /// <summary>
            /// Creates a new PMI_Supervisor  folder.
            /// </summary>
            public PMI_SupervisorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PMI_Supervisor", "/mobileapp[@title='pk.com.tradetracker']", parentFolder, 30000, null, false, "fd56243c-ade9-476f-af68-74733305a57b", "")
            {
                _list = new PMISupervisorRepositoryFolders.ListFolder(this);
                _list1 = new PMISupervisorRepositoryFolders.List1Folder(this);
                _validate_appstartingscreenInfo = new RepoItemInfo(this, "Validate_AppStartingScreen", "form[@title='MainScreenSupervisor']/container[@rid='content']//text[@caption='WELCOME']", 30000, null, "1b5b46c7-8f11-4019-8775-5af1d7edccc3");
                _workreview_radiobuttonInfo = new RepoItemInfo(this, "WorkReview_RadioButton", "form[@title='MainScreenSupervisor']/container[@rid='content']//radiobutton[@text='WR']", 30000, null, "f037047c-61c7-453a-8895-4d75fa58264c");
                _workwith_radiobuttonInfo = new RepoItemInfo(this, "WorkWith_RadioButton", "form[@title='MainScreenSupervisor']/container[@rid='content']//radiobutton[@text='WW']", 30000, null, "9ac999d9-0218-4399-85e4-83e02376c6d3");
                _buttonsubmitInfo = new RepoItemInfo(this, "ButtonSubmit", "form[@title='MainScreenSupervisor']/container[@rid='content']//button[@text=' Submit ']", 30000, null, "bf59d7fd-a555-4c9a-8b41-04372acbefd2");
                _validation_okbuttonInfo = new RepoItemInfo(this, "Validation_OKButton", "form[@title='Info']/container[@rid='content']//button[@resourceid='R.string.yes']", 30000, null, "a74c639d-e7c9-4ac7-adb9-0ba809a2500d");
                _attendance_buttonInfo = new RepoItemInfo(this, "Attendance_Button", "form[@title='MainScreenSupervisor']/container[@rid='content']/?/?/container[@containertype='Linear']/container[2]/container[@containertype='Relative']/button[@text=' Attendance ']", 30000, null, "06ef7c04-173f-4f0e-93c5-7087f3dea2d8");
                _validate_attendancescreenInfo = new RepoItemInfo(this, "Validate_AttendanceScreen", "form[@title='AttendenceListScreen']/container[@rid='content']//text[@caption='Attendance']", 30000, null, "ab555116-9ae6-47b2-99b1-d5ad884eee88");
                _merchandisers_attendancelistInfo = new RepoItemInfo(this, "Merchandisers_AttendanceList", "form[@title='AttendenceListScreen']//list[@rid='list']", 30000, null, "2b31c732-0589-4f8b-8d2a-8d1106b76b2f");
                _validate_merchandiserslistscreenInfo = new RepoItemInfo(this, "Validate_MERCHANDISERSLISTScreen", "form[@title='MerchListScreen']/container[@rid='content']//text[@caption='MERCHANDISERS LIST']", 30000, null, "1893e536-db46-4407-a746-1de9f3b600cf");
                _merchandisers_listInfo = new RepoItemInfo(this, "Merchandisers_List", "form[@title='MerchListScreen']//list[@rid='list']", 30000, null, "477a4856-c562-48ac-a1f3-2499b07328e0");
                _validate_routelistscreenInfo = new RepoItemInfo(this, "Validate_ROUTELISTScreen", "form[@title='RouteListScreen']/container[@rid='content']//text[@caption='ROUTE LIST']", 30000, null, "5f7cae13-3b91-468d-a8f0-d9ead14c7d89");
                _route_listInfo = new RepoItemInfo(this, "Route_List", "form[@title='RouteListScreen']//list[@rid='list']", 30000, null, "724f5af0-998c-47d3-a7f5-c2570195f316");
                _shopslist_validationInfo = new ShopsList_validationInfoClass(this);
                _validate_shopslistscreenInfo = new RepoItemInfo(this, "Validate_ShopsListScreen", "form[@title='ShopsListScreen']/container[@rid='content']//text[@caption='Shops List']", 30000, null, "cafb2cca-c77c-4344-8920-4f3c0441aae4");
                _shops_listInfo = new RepoItemInfo(this, "Shops_List", "form[@title='ShopsListScreen']//list[@rid='list']", 30000, null, "92bd42e9-c9ae-496e-af21-863b3e46c5c1");
                _validate_infopopupInfo = new RepoItemInfo(this, "Validate_InfoPopUp", "form[@title='Info']", 30000, null, "221c7aa4-f23b-4874-97a2-bf3cb6eb57e8");
                _validate_shopdetailsformInfo = new RepoItemInfo(this, "Validate_ShopDetailsForm", "form[@title='(none)']", 30000, null, "41819b1d-1c9d-49bc-9e63-4e9afaf9233e");
                _shopdetailsInfo = new RepoItemInfo(this, "ShopDetails", "form[@title='(none)']//list/container[1]", 30000, null, "4a94db0b-632d-4aa3-bd1f-69b34b3ed721");
                _validate_proceedshopformInfo = new RepoItemInfo(this, "Validate_ProceedShopForm", "form[@title='(none)']/container[@rid='content']", 30000, null, "09a24892-db3e-4c14-9bab-6df61155e45d");
                _proceedbuttonInfo = new RepoItemInfo(this, "ProceedButton", "form[@title='(none)']/container[@rid='content']//button[@text='Proceed']", 30000, null, "3ebcdd59-96a7-4eb8-9223-64a663ca16f3");
                _validate_tradetrackerscreenInfo = new RepoItemInfo(this, "Validate_TradeTrackerScreen", "?/?/toolbar/?/?/text[@caption='Trade Tracker']", 30000, null, "c56619be-0444-4a54-b953-715e5637b824");
                _checkinbuttonInfo = new RepoItemInfo(this, "CheckInButton", "form[@title='GpsCoordinates']/container[@rid='content']//picture", 30000, null, "292dfa67-1a13-45ca-995e-f037a8f87b3b");
                _shopremarks_listInfo = new RepoItemInfo(this, "ShopRemarks_List", "form[@title='']/container[@rid='content']//container[@rid='custom']/?/?/list[@rid='list']", 30000, null, "0c30c2f8-6171-41fc-be43-ed30d7dd3932");
                _userlocationisincorrectInfo = new RepoItemInfo(this, "UserLocationIsIncorrect", "form[@title='']/container//list/container", 30000, null, "1b417958-96e6-4646-abc3-33a56593fe34");
                _shopopenInfo = new RepoItemInfo(this, "ShopOpen", "form[@title='']/container[@rid='content']//list[@rid='list']/container[1]", 30000, null, "ec56b018-a7fa-4dbe-b0f0-d87890865b28");
                _validate_camerascreenInfo = new RepoItemInfo(this, "Validate_CameraScreen", "form[@title='CameraActivity']/?/?/container[@containertype='Relative']/container[2]", 30000, null, "a08fc434-f3a1-40c6-bf13-9bcdf92118e2");
                _takephotoInfo = new RepoItemInfo(this, "TakePhoto", "form[@title='CameraActivity']/container[@rid='content']//button[@text='Take Photo']", 30000, null, "53010911-f0b0-452e-8668-d775f16e4408");
                _buttondoneInfo = new RepoItemInfo(this, "ButtonDone", "form[@title='CameraActivity']/container[@rid='content']//button[@text='  Done  ']", 30000, null, "451911a3-f2fe-45c6-bffc-2637a8d27171");
                _yesbuttonInfo = new RepoItemInfo(this, "YesButton", "form[@title='Info']/container[@rid='content']//button[@rid='button1']", 30000, null, "8ca87ed1-3bb6-43ca-8433-b50ef9929721");
                _nobuttonInfo = new RepoItemInfo(this, "NoButton", "form[@title='Info']/container[@rid='content']//button[@rid='button2']", 30000, null, "30e3c6cd-77d4-469a-b635-d651fa3d5b42");
                _validate_nontkshopscreenInfo = new RepoItemInfo(this, "Validate_NonTKShopScreen", "form[@title='MainShopOptionsListScreen']/container[@rid='content']//text[@caption='Non-TK']", 30000, null, "a98c99e0-5c99-482c-ae56-33fe0fc4e812");
                _tposmapplicationInfo = new RepoItemInfo(this, "TPOSMApplication", "form[@title='MainShopOptionsListScreen']//list[@rid='list']/container[1]", 30000, null, "2da17f51-208c-4269-a5b1-3f59ac5e2159");
                _validate_tposmapplicationscreenInfo = new RepoItemInfo(this, "Validate_TPOSMApplicationScreen", "form[@title='MainTouchPointListScreen']/container[@rid='content']//text[@caption='TPOSM Application']", 30000, null, "9efa5915-3cae-47c4-a64a-b4ab10364afc");
                _tposmdeploymentInfo = new RepoItemInfo(this, "TPOSMDeployment", "form[@title='MainTouchPointListScreen']//list[@rid='list']/container[@containertype='Relative']", 30000, null, "4b2b9bed-227f-42d4-ac4e-955fdecca5e9");
                _validate_tposmdeploymentscreenInfo = new RepoItemInfo(this, "Validate_TPOSMDeploymentScreen", "form[@title='TouchPointListScreen']/container[@rid='content']//text[@caption='TPOSM']", 30000, null, "2f46a54e-e816-45d9-817d-d081589aa36e");
                _tposm_listInfo = new RepoItemInfo(this, "TPOSM_List", "form[@title='TouchPointListScreen']//list[@rid='list']", 100, null, "e7e5575b-3717-4bc8-8ff9-b2e444a99b3f");
                _validate_tposmscreenInfo = new RepoItemInfo(this, "Validate_TPOSMScreen", "form[@title~'^TouchPointRemarksListScre']/container[@rid='content']//text[@caption='TPOSM']", 30000, null, "3a494590-5a6a-4d22-8bdf-671643985d87");
                _tposm1_yesInfo = new RepoItemInfo(this, "TPOSM1_Yes", "?/?/container/?/?/list[@rid='list']/container[1]", 30000, null, "6ad974b2-2658-4872-9ce2-f3ae9da8f429");
                _tposm_noInfo = new RepoItemInfo(this, "TPOSM_No", "form[@title~'^TouchPointRemarksListScre']//list[@rid='list']/container[2]", 30000, null, "b18d9122-c4f9-484a-a731-c1cec2cc664f");
                _tposm2_yesInfo = new RepoItemInfo(this, "TPOSM2_Yes", "form[@title~'^TouchPointRemarksListScre']//list[@rid='list']/container[1]", 30000, null, "c313c467-2820-4c52-b4ee-d3db22110ac7");
                _validate_tposmquantitypopupInfo = new RepoItemInfo(this, "Validate_TPOSMQuantityPopUp", "form[@title='']", 30000, null, "0a8f6309-c3d5-4eeb-9b2c-97ac8f5c3742");
                _tposmquantity_edittextfieldInfo = new RepoItemInfo(this, "TPOSMQuantity_EditTextField", "form[@title='']/container[@rid='content']//container[@rid='custom']/text", 30000, null, "3feeeb25-8230-48e6-9576-d08322c1093a");
                _tposmquantity_okbuttonInfo = new RepoItemInfo(this, "TPOSMQuantity_OKButton", "form[@title='']/container[@rid='content']//button[@rid='button1']", 30000, null, "e27cc19d-20f1-48fb-8b91-50a247404ad8");
                _tposm_takepicture1Info = new RepoItemInfo(this, "TPOSM_TakePicture1", "form[@title='MainTouchPointListScreen']/container[@rid='content']/container/container[2]/button[1]", 30000, null, "50948618-4726-4d56-b33a-9764c50851f4");
                _tposm_takepicture2Info = new RepoItemInfo(this, "TPOSM_TakePicture2", "form[@title='MainTouchPointListScreen']/container[@rid='content']/container/container[2]/button[2]", 30000, null, "9d377727-e82b-4903-a911-7f6ff5e55171");
                _availabilitycheckInfo = new RepoItemInfo(this, "AvailabilityCheck", "form[@title='MainShopOptionsListScreen']//list[@rid='list']/container[2]", 30000, null, "ae81bed6-f7dc-4004-9ccd-535a1280d341");
                _validate_availabilitycheckscreenInfo = new RepoItemInfo(this, "Validate_AVAILABILITYCHECKScreen", "form[@title~'^InformationCollectionScre']/container[@rid='content']//text[@caption='AVAILABILITY CHECK']", 30000, null, "393237b7-ced8-4d87-8ebd-1210c7d416c1");
                _availabilitycheck_listInfo = new RepoItemInfo(this, "AvailabilityCheck_List", "form[@title~'^InformationCollectionScre']/container[@rid='content']/?/?/container[@containertype='ScrollView']/container[@containertype='Linear']", 30000, null, "f138f831-4b63-4831-9685-69a4e19b9778");
                _nontkmodules_listInfo = new RepoItemInfo(this, "NonTKModules_List", "form[@title='MainShopOptionsListScreen']//list[@rid='list']", 30000, null, "bf4e6e3b-55f7-4e0b-a6db-e824a361af1f");
            }

            /// <summary>
            /// The ShopsList_validationInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("5b5e20e1-b1cb-410b-9729-e04314ea2e1e")]
            public class ShopsList_validationInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ShopsList_validationInfoClass class constructor.
                /// </summary>
                public ShopsList_validationInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ShopsList_validation", "form[@title='ShopsListScreen']/?/?/container[@containertype='Linear']/container[1]", 30000, null, "5b5e20e1-b1cb-410b-9729-e04314ea2e1e")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("873277d8-7b7d-4d19-932f-2b4f07557dfa")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("873277d8-7b7d-4d19-932f-2b4f07557dfa");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("873277d8-7b7d-4d19-932f-2b4f07557dfa")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("873277d8-7b7d-4d19-932f-2b4f07557dfa", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd56243c-ade9-476f-af68-74733305a57b")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd56243c-ade9-476f-af68-74733305a57b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Validate_AppStartingScreen item.
            /// </summary>
            [RepositoryItem("1b5b46c7-8f11-4019-8775-5af1d7edccc3")]
            public virtual Ranorex.Text Validate_AppStartingScreen
            {
                get
                {
                    return _validate_appstartingscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_AppStartingScreen item info.
            /// </summary>
            [RepositoryItemInfo("1b5b46c7-8f11-4019-8775-5af1d7edccc3")]
            public virtual RepoItemInfo Validate_AppStartingScreenInfo
            {
                get
                {
                    return _validate_appstartingscreenInfo;
                }
            }

            /// <summary>
            /// The WorkReview_RadioButton item.
            /// </summary>
            [RepositoryItem("f037047c-61c7-453a-8895-4d75fa58264c")]
            public virtual Ranorex.RadioButton WorkReview_RadioButton
            {
                get
                {
                    return _workreview_radiobuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The WorkReview_RadioButton item info.
            /// </summary>
            [RepositoryItemInfo("f037047c-61c7-453a-8895-4d75fa58264c")]
            public virtual RepoItemInfo WorkReview_RadioButtonInfo
            {
                get
                {
                    return _workreview_radiobuttonInfo;
                }
            }

            /// <summary>
            /// The WorkWith_RadioButton item.
            /// </summary>
            [RepositoryItem("9ac999d9-0218-4399-85e4-83e02376c6d3")]
            public virtual Ranorex.RadioButton WorkWith_RadioButton
            {
                get
                {
                    return _workwith_radiobuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The WorkWith_RadioButton item info.
            /// </summary>
            [RepositoryItemInfo("9ac999d9-0218-4399-85e4-83e02376c6d3")]
            public virtual RepoItemInfo WorkWith_RadioButtonInfo
            {
                get
                {
                    return _workwith_radiobuttonInfo;
                }
            }

            /// <summary>
            /// The ButtonSubmit item.
            /// </summary>
            [RepositoryItem("bf59d7fd-a555-4c9a-8b41-04372acbefd2")]
            public virtual Ranorex.Button ButtonSubmit
            {
                get
                {
                    return _buttonsubmitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSubmit item info.
            /// </summary>
            [RepositoryItemInfo("bf59d7fd-a555-4c9a-8b41-04372acbefd2")]
            public virtual RepoItemInfo ButtonSubmitInfo
            {
                get
                {
                    return _buttonsubmitInfo;
                }
            }

            /// <summary>
            /// The Validation_OKButton item.
            /// </summary>
            [RepositoryItem("a74c639d-e7c9-4ac7-adb9-0ba809a2500d")]
            public virtual Ranorex.Button Validation_OKButton
            {
                get
                {
                    return _validation_okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Validation_OKButton item info.
            /// </summary>
            [RepositoryItemInfo("a74c639d-e7c9-4ac7-adb9-0ba809a2500d")]
            public virtual RepoItemInfo Validation_OKButtonInfo
            {
                get
                {
                    return _validation_okbuttonInfo;
                }
            }

            /// <summary>
            /// The Attendance_Button item.
            /// </summary>
            [RepositoryItem("06ef7c04-173f-4f0e-93c5-7087f3dea2d8")]
            public virtual Ranorex.Button Attendance_Button
            {
                get
                {
                    return _attendance_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Attendance_Button item info.
            /// </summary>
            [RepositoryItemInfo("06ef7c04-173f-4f0e-93c5-7087f3dea2d8")]
            public virtual RepoItemInfo Attendance_ButtonInfo
            {
                get
                {
                    return _attendance_buttonInfo;
                }
            }

            /// <summary>
            /// The Validate_AttendanceScreen item.
            /// </summary>
            [RepositoryItem("ab555116-9ae6-47b2-99b1-d5ad884eee88")]
            public virtual Ranorex.Text Validate_AttendanceScreen
            {
                get
                {
                    return _validate_attendancescreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_AttendanceScreen item info.
            /// </summary>
            [RepositoryItemInfo("ab555116-9ae6-47b2-99b1-d5ad884eee88")]
            public virtual RepoItemInfo Validate_AttendanceScreenInfo
            {
                get
                {
                    return _validate_attendancescreenInfo;
                }
            }

            /// <summary>
            /// The Merchandisers_AttendanceList item.
            /// </summary>
            [RepositoryItem("2b31c732-0589-4f8b-8d2a-8d1106b76b2f")]
            public virtual Ranorex.List Merchandisers_AttendanceList
            {
                get
                {
                    return _merchandisers_attendancelistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Merchandisers_AttendanceList item info.
            /// </summary>
            [RepositoryItemInfo("2b31c732-0589-4f8b-8d2a-8d1106b76b2f")]
            public virtual RepoItemInfo Merchandisers_AttendanceListInfo
            {
                get
                {
                    return _merchandisers_attendancelistInfo;
                }
            }

            /// <summary>
            /// The Validate_MERCHANDISERSLISTScreen item.
            /// </summary>
            [RepositoryItem("1893e536-db46-4407-a746-1de9f3b600cf")]
            public virtual Ranorex.Text Validate_MERCHANDISERSLISTScreen
            {
                get
                {
                    return _validate_merchandiserslistscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_MERCHANDISERSLISTScreen item info.
            /// </summary>
            [RepositoryItemInfo("1893e536-db46-4407-a746-1de9f3b600cf")]
            public virtual RepoItemInfo Validate_MERCHANDISERSLISTScreenInfo
            {
                get
                {
                    return _validate_merchandiserslistscreenInfo;
                }
            }

            /// <summary>
            /// The Merchandisers_List item.
            /// </summary>
            [RepositoryItem("477a4856-c562-48ac-a1f3-2499b07328e0")]
            public virtual Ranorex.List Merchandisers_List
            {
                get
                {
                    return _merchandisers_listInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Merchandisers_List item info.
            /// </summary>
            [RepositoryItemInfo("477a4856-c562-48ac-a1f3-2499b07328e0")]
            public virtual RepoItemInfo Merchandisers_ListInfo
            {
                get
                {
                    return _merchandisers_listInfo;
                }
            }

            /// <summary>
            /// The Validate_ROUTELISTScreen item.
            /// </summary>
            [RepositoryItem("5f7cae13-3b91-468d-a8f0-d9ead14c7d89")]
            public virtual Ranorex.Text Validate_ROUTELISTScreen
            {
                get
                {
                    return _validate_routelistscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_ROUTELISTScreen item info.
            /// </summary>
            [RepositoryItemInfo("5f7cae13-3b91-468d-a8f0-d9ead14c7d89")]
            public virtual RepoItemInfo Validate_ROUTELISTScreenInfo
            {
                get
                {
                    return _validate_routelistscreenInfo;
                }
            }

            /// <summary>
            /// The Route_List item.
            /// </summary>
            [RepositoryItem("724f5af0-998c-47d3-a7f5-c2570195f316")]
            public virtual Ranorex.List Route_List
            {
                get
                {
                    return _route_listInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Route_List item info.
            /// </summary>
            [RepositoryItemInfo("724f5af0-998c-47d3-a7f5-c2570195f316")]
            public virtual RepoItemInfo Route_ListInfo
            {
                get
                {
                    return _route_listInfo;
                }
            }

            /// <summary>
            /// The ShopsList_validation item.
            /// </summary>
            [RepositoryItem("5b5e20e1-b1cb-410b-9729-e04314ea2e1e")]
            public virtual Ranorex.Container ShopsList_validation
            {
                get
                {
                    return _shopslist_validationInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ShopsList_validation item info.
            /// </summary>
            [RepositoryItemInfo("5b5e20e1-b1cb-410b-9729-e04314ea2e1e")]
            public virtual ShopsList_validationInfoClass ShopsList_validationInfo
            {
                get
                {
                    return _shopslist_validationInfo;
                }
            }

            /// <summary>
            /// The Validate_ShopsListScreen item.
            /// </summary>
            [RepositoryItem("cafb2cca-c77c-4344-8920-4f3c0441aae4")]
            public virtual Ranorex.Text Validate_ShopsListScreen
            {
                get
                {
                    return _validate_shopslistscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_ShopsListScreen item info.
            /// </summary>
            [RepositoryItemInfo("cafb2cca-c77c-4344-8920-4f3c0441aae4")]
            public virtual RepoItemInfo Validate_ShopsListScreenInfo
            {
                get
                {
                    return _validate_shopslistscreenInfo;
                }
            }

            /// <summary>
            /// The Shops_List item.
            /// </summary>
            [RepositoryItem("92bd42e9-c9ae-496e-af21-863b3e46c5c1")]
            public virtual Ranorex.List Shops_List
            {
                get
                {
                    return _shops_listInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Shops_List item info.
            /// </summary>
            [RepositoryItemInfo("92bd42e9-c9ae-496e-af21-863b3e46c5c1")]
            public virtual RepoItemInfo Shops_ListInfo
            {
                get
                {
                    return _shops_listInfo;
                }
            }

            /// <summary>
            /// The Validate_InfoPopUp item.
            /// </summary>
            [RepositoryItem("221c7aa4-f23b-4874-97a2-bf3cb6eb57e8")]
            public virtual Ranorex.Form Validate_InfoPopUp
            {
                get
                {
                    return _validate_infopopupInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Validate_InfoPopUp item info.
            /// </summary>
            [RepositoryItemInfo("221c7aa4-f23b-4874-97a2-bf3cb6eb57e8")]
            public virtual RepoItemInfo Validate_InfoPopUpInfo
            {
                get
                {
                    return _validate_infopopupInfo;
                }
            }

            /// <summary>
            /// The Validate_ShopDetailsForm item.
            /// </summary>
            [RepositoryItem("41819b1d-1c9d-49bc-9e63-4e9afaf9233e")]
            public virtual Ranorex.Form Validate_ShopDetailsForm
            {
                get
                {
                    return _validate_shopdetailsformInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Validate_ShopDetailsForm item info.
            /// </summary>
            [RepositoryItemInfo("41819b1d-1c9d-49bc-9e63-4e9afaf9233e")]
            public virtual RepoItemInfo Validate_ShopDetailsFormInfo
            {
                get
                {
                    return _validate_shopdetailsformInfo;
                }
            }

            /// <summary>
            /// The ShopDetails item.
            /// </summary>
            [RepositoryItem("4a94db0b-632d-4aa3-bd1f-69b34b3ed721")]
            public virtual Ranorex.Container ShopDetails
            {
                get
                {
                    return _shopdetailsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ShopDetails item info.
            /// </summary>
            [RepositoryItemInfo("4a94db0b-632d-4aa3-bd1f-69b34b3ed721")]
            public virtual RepoItemInfo ShopDetailsInfo
            {
                get
                {
                    return _shopdetailsInfo;
                }
            }

            /// <summary>
            /// The Validate_ProceedShopForm item.
            /// </summary>
            [RepositoryItem("09a24892-db3e-4c14-9bab-6df61155e45d")]
            public virtual Ranorex.Container Validate_ProceedShopForm
            {
                get
                {
                    return _validate_proceedshopformInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Validate_ProceedShopForm item info.
            /// </summary>
            [RepositoryItemInfo("09a24892-db3e-4c14-9bab-6df61155e45d")]
            public virtual RepoItemInfo Validate_ProceedShopFormInfo
            {
                get
                {
                    return _validate_proceedshopformInfo;
                }
            }

            /// <summary>
            /// The ProceedButton item.
            /// </summary>
            [RepositoryItem("3ebcdd59-96a7-4eb8-9223-64a663ca16f3")]
            public virtual Ranorex.Button ProceedButton
            {
                get
                {
                    return _proceedbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ProceedButton item info.
            /// </summary>
            [RepositoryItemInfo("3ebcdd59-96a7-4eb8-9223-64a663ca16f3")]
            public virtual RepoItemInfo ProceedButtonInfo
            {
                get
                {
                    return _proceedbuttonInfo;
                }
            }

            /// <summary>
            /// The Validate_TradeTrackerScreen item.
            /// </summary>
            [RepositoryItem("c56619be-0444-4a54-b953-715e5637b824")]
            public virtual Ranorex.Text Validate_TradeTrackerScreen
            {
                get
                {
                    return _validate_tradetrackerscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_TradeTrackerScreen item info.
            /// </summary>
            [RepositoryItemInfo("c56619be-0444-4a54-b953-715e5637b824")]
            public virtual RepoItemInfo Validate_TradeTrackerScreenInfo
            {
                get
                {
                    return _validate_tradetrackerscreenInfo;
                }
            }

            /// <summary>
            /// The CheckInButton item.
            /// </summary>
            [RepositoryItem("292dfa67-1a13-45ca-995e-f037a8f87b3b")]
            public virtual Ranorex.Picture CheckInButton
            {
                get
                {
                    return _checkinbuttonInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The CheckInButton item info.
            /// </summary>
            [RepositoryItemInfo("292dfa67-1a13-45ca-995e-f037a8f87b3b")]
            public virtual RepoItemInfo CheckInButtonInfo
            {
                get
                {
                    return _checkinbuttonInfo;
                }
            }

            /// <summary>
            /// The ShopRemarks_List item.
            /// </summary>
            [RepositoryItem("0c30c2f8-6171-41fc-be43-ed30d7dd3932")]
            public virtual Ranorex.List ShopRemarks_List
            {
                get
                {
                    return _shopremarks_listInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ShopRemarks_List item info.
            /// </summary>
            [RepositoryItemInfo("0c30c2f8-6171-41fc-be43-ed30d7dd3932")]
            public virtual RepoItemInfo ShopRemarks_ListInfo
            {
                get
                {
                    return _shopremarks_listInfo;
                }
            }

            /// <summary>
            /// The UserLocationIsIncorrect item.
            /// </summary>
            [RepositoryItem("1b417958-96e6-4646-abc3-33a56593fe34")]
            public virtual Ranorex.Container UserLocationIsIncorrect
            {
                get
                {
                    return _userlocationisincorrectInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The UserLocationIsIncorrect item info.
            /// </summary>
            [RepositoryItemInfo("1b417958-96e6-4646-abc3-33a56593fe34")]
            public virtual RepoItemInfo UserLocationIsIncorrectInfo
            {
                get
                {
                    return _userlocationisincorrectInfo;
                }
            }

            /// <summary>
            /// The ShopOpen item.
            /// </summary>
            [RepositoryItem("ec56b018-a7fa-4dbe-b0f0-d87890865b28")]
            public virtual Ranorex.Container ShopOpen
            {
                get
                {
                    return _shopopenInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ShopOpen item info.
            /// </summary>
            [RepositoryItemInfo("ec56b018-a7fa-4dbe-b0f0-d87890865b28")]
            public virtual RepoItemInfo ShopOpenInfo
            {
                get
                {
                    return _shopopenInfo;
                }
            }

            /// <summary>
            /// The Validate_CameraScreen item.
            /// </summary>
            [RepositoryItem("a08fc434-f3a1-40c6-bf13-9bcdf92118e2")]
            public virtual Ranorex.Container Validate_CameraScreen
            {
                get
                {
                    return _validate_camerascreenInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Validate_CameraScreen item info.
            /// </summary>
            [RepositoryItemInfo("a08fc434-f3a1-40c6-bf13-9bcdf92118e2")]
            public virtual RepoItemInfo Validate_CameraScreenInfo
            {
                get
                {
                    return _validate_camerascreenInfo;
                }
            }

            /// <summary>
            /// The TakePhoto item.
            /// </summary>
            [RepositoryItem("53010911-f0b0-452e-8668-d775f16e4408")]
            public virtual Ranorex.Button TakePhoto
            {
                get
                {
                    return _takephotoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TakePhoto item info.
            /// </summary>
            [RepositoryItemInfo("53010911-f0b0-452e-8668-d775f16e4408")]
            public virtual RepoItemInfo TakePhotoInfo
            {
                get
                {
                    return _takephotoInfo;
                }
            }

            /// <summary>
            /// The ButtonDone item.
            /// </summary>
            [RepositoryItem("451911a3-f2fe-45c6-bffc-2637a8d27171")]
            public virtual Ranorex.Button ButtonDone
            {
                get
                {
                    return _buttondoneInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonDone item info.
            /// </summary>
            [RepositoryItemInfo("451911a3-f2fe-45c6-bffc-2637a8d27171")]
            public virtual RepoItemInfo ButtonDoneInfo
            {
                get
                {
                    return _buttondoneInfo;
                }
            }

            /// <summary>
            /// The YesButton item.
            /// </summary>
            [RepositoryItem("8ca87ed1-3bb6-43ca-8433-b50ef9929721")]
            public virtual Ranorex.Button YesButton
            {
                get
                {
                    return _yesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YesButton item info.
            /// </summary>
            [RepositoryItemInfo("8ca87ed1-3bb6-43ca-8433-b50ef9929721")]
            public virtual RepoItemInfo YesButtonInfo
            {
                get
                {
                    return _yesbuttonInfo;
                }
            }

            /// <summary>
            /// The NoButton item.
            /// </summary>
            [RepositoryItem("30e3c6cd-77d4-469a-b635-d651fa3d5b42")]
            public virtual Ranorex.Button NoButton
            {
                get
                {
                    return _nobuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NoButton item info.
            /// </summary>
            [RepositoryItemInfo("30e3c6cd-77d4-469a-b635-d651fa3d5b42")]
            public virtual RepoItemInfo NoButtonInfo
            {
                get
                {
                    return _nobuttonInfo;
                }
            }

            /// <summary>
            /// The Validate_NonTKShopScreen item.
            /// </summary>
            [RepositoryItem("a98c99e0-5c99-482c-ae56-33fe0fc4e812")]
            public virtual Ranorex.Text Validate_NonTKShopScreen
            {
                get
                {
                    return _validate_nontkshopscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_NonTKShopScreen item info.
            /// </summary>
            [RepositoryItemInfo("a98c99e0-5c99-482c-ae56-33fe0fc4e812")]
            public virtual RepoItemInfo Validate_NonTKShopScreenInfo
            {
                get
                {
                    return _validate_nontkshopscreenInfo;
                }
            }

            /// <summary>
            /// The TPOSMApplication item.
            /// </summary>
            [RepositoryItem("2da17f51-208c-4269-a5b1-3f59ac5e2159")]
            public virtual Ranorex.Container TPOSMApplication
            {
                get
                {
                    return _tposmapplicationInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TPOSMApplication item info.
            /// </summary>
            [RepositoryItemInfo("2da17f51-208c-4269-a5b1-3f59ac5e2159")]
            public virtual RepoItemInfo TPOSMApplicationInfo
            {
                get
                {
                    return _tposmapplicationInfo;
                }
            }

            /// <summary>
            /// The Validate_TPOSMApplicationScreen item.
            /// </summary>
            [RepositoryItem("9efa5915-3cae-47c4-a64a-b4ab10364afc")]
            public virtual Ranorex.Text Validate_TPOSMApplicationScreen
            {
                get
                {
                    return _validate_tposmapplicationscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_TPOSMApplicationScreen item info.
            /// </summary>
            [RepositoryItemInfo("9efa5915-3cae-47c4-a64a-b4ab10364afc")]
            public virtual RepoItemInfo Validate_TPOSMApplicationScreenInfo
            {
                get
                {
                    return _validate_tposmapplicationscreenInfo;
                }
            }

            /// <summary>
            /// The TPOSMDeployment item.
            /// </summary>
            [RepositoryItem("4b2b9bed-227f-42d4-ac4e-955fdecca5e9")]
            public virtual Ranorex.Container TPOSMDeployment
            {
                get
                {
                    return _tposmdeploymentInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TPOSMDeployment item info.
            /// </summary>
            [RepositoryItemInfo("4b2b9bed-227f-42d4-ac4e-955fdecca5e9")]
            public virtual RepoItemInfo TPOSMDeploymentInfo
            {
                get
                {
                    return _tposmdeploymentInfo;
                }
            }

            /// <summary>
            /// The Validate_TPOSMDeploymentScreen item.
            /// </summary>
            [RepositoryItem("2f46a54e-e816-45d9-817d-d081589aa36e")]
            public virtual Ranorex.Text Validate_TPOSMDeploymentScreen
            {
                get
                {
                    return _validate_tposmdeploymentscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_TPOSMDeploymentScreen item info.
            /// </summary>
            [RepositoryItemInfo("2f46a54e-e816-45d9-817d-d081589aa36e")]
            public virtual RepoItemInfo Validate_TPOSMDeploymentScreenInfo
            {
                get
                {
                    return _validate_tposmdeploymentscreenInfo;
                }
            }

            /// <summary>
            /// The TPOSM_List item.
            /// </summary>
            [RepositoryItem("e7e5575b-3717-4bc8-8ff9-b2e444a99b3f")]
            public virtual Ranorex.List TPOSM_List
            {
                get
                {
                    return _tposm_listInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The TPOSM_List item info.
            /// </summary>
            [RepositoryItemInfo("e7e5575b-3717-4bc8-8ff9-b2e444a99b3f")]
            public virtual RepoItemInfo TPOSM_ListInfo
            {
                get
                {
                    return _tposm_listInfo;
                }
            }

            /// <summary>
            /// The Validate_TPOSMScreen item.
            /// </summary>
            [RepositoryItem("3a494590-5a6a-4d22-8bdf-671643985d87")]
            public virtual Ranorex.Text Validate_TPOSMScreen
            {
                get
                {
                    return _validate_tposmscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_TPOSMScreen item info.
            /// </summary>
            [RepositoryItemInfo("3a494590-5a6a-4d22-8bdf-671643985d87")]
            public virtual RepoItemInfo Validate_TPOSMScreenInfo
            {
                get
                {
                    return _validate_tposmscreenInfo;
                }
            }

            /// <summary>
            /// The TPOSM1_Yes item.
            /// </summary>
            [RepositoryItem("6ad974b2-2658-4872-9ce2-f3ae9da8f429")]
            public virtual Ranorex.Container TPOSM1_Yes
            {
                get
                {
                    return _tposm1_yesInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TPOSM1_Yes item info.
            /// </summary>
            [RepositoryItemInfo("6ad974b2-2658-4872-9ce2-f3ae9da8f429")]
            public virtual RepoItemInfo TPOSM1_YesInfo
            {
                get
                {
                    return _tposm1_yesInfo;
                }
            }

            /// <summary>
            /// The TPOSM_No item.
            /// </summary>
            [RepositoryItem("b18d9122-c4f9-484a-a731-c1cec2cc664f")]
            public virtual Ranorex.Container TPOSM_No
            {
                get
                {
                    return _tposm_noInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TPOSM_No item info.
            /// </summary>
            [RepositoryItemInfo("b18d9122-c4f9-484a-a731-c1cec2cc664f")]
            public virtual RepoItemInfo TPOSM_NoInfo
            {
                get
                {
                    return _tposm_noInfo;
                }
            }

            /// <summary>
            /// The TPOSM2_Yes item.
            /// </summary>
            [RepositoryItem("c313c467-2820-4c52-b4ee-d3db22110ac7")]
            public virtual Ranorex.Container TPOSM2_Yes
            {
                get
                {
                    return _tposm2_yesInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TPOSM2_Yes item info.
            /// </summary>
            [RepositoryItemInfo("c313c467-2820-4c52-b4ee-d3db22110ac7")]
            public virtual RepoItemInfo TPOSM2_YesInfo
            {
                get
                {
                    return _tposm2_yesInfo;
                }
            }

            /// <summary>
            /// The Validate_TPOSMQuantityPopUp item.
            /// </summary>
            [RepositoryItem("0a8f6309-c3d5-4eeb-9b2c-97ac8f5c3742")]
            public virtual Ranorex.Form Validate_TPOSMQuantityPopUp
            {
                get
                {
                    return _validate_tposmquantitypopupInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Validate_TPOSMQuantityPopUp item info.
            /// </summary>
            [RepositoryItemInfo("0a8f6309-c3d5-4eeb-9b2c-97ac8f5c3742")]
            public virtual RepoItemInfo Validate_TPOSMQuantityPopUpInfo
            {
                get
                {
                    return _validate_tposmquantitypopupInfo;
                }
            }

            /// <summary>
            /// The TPOSMQuantity_EditTextField item.
            /// </summary>
            [RepositoryItem("3feeeb25-8230-48e6-9576-d08322c1093a")]
            public virtual Ranorex.Text TPOSMQuantity_EditTextField
            {
                get
                {
                    return _tposmquantity_edittextfieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TPOSMQuantity_EditTextField item info.
            /// </summary>
            [RepositoryItemInfo("3feeeb25-8230-48e6-9576-d08322c1093a")]
            public virtual RepoItemInfo TPOSMQuantity_EditTextFieldInfo
            {
                get
                {
                    return _tposmquantity_edittextfieldInfo;
                }
            }

            /// <summary>
            /// The TPOSMQuantity_OKButton item.
            /// </summary>
            [RepositoryItem("e27cc19d-20f1-48fb-8b91-50a247404ad8")]
            public virtual Ranorex.Button TPOSMQuantity_OKButton
            {
                get
                {
                    return _tposmquantity_okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TPOSMQuantity_OKButton item info.
            /// </summary>
            [RepositoryItemInfo("e27cc19d-20f1-48fb-8b91-50a247404ad8")]
            public virtual RepoItemInfo TPOSMQuantity_OKButtonInfo
            {
                get
                {
                    return _tposmquantity_okbuttonInfo;
                }
            }

            /// <summary>
            /// The TPOSM_TakePicture1 item.
            /// </summary>
            [RepositoryItem("50948618-4726-4d56-b33a-9764c50851f4")]
            public virtual Ranorex.Button TPOSM_TakePicture1
            {
                get
                {
                    return _tposm_takepicture1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TPOSM_TakePicture1 item info.
            /// </summary>
            [RepositoryItemInfo("50948618-4726-4d56-b33a-9764c50851f4")]
            public virtual RepoItemInfo TPOSM_TakePicture1Info
            {
                get
                {
                    return _tposm_takepicture1Info;
                }
            }

            /// <summary>
            /// The TPOSM_TakePicture2 item.
            /// </summary>
            [RepositoryItem("9d377727-e82b-4903-a911-7f6ff5e55171")]
            public virtual Ranorex.Button TPOSM_TakePicture2
            {
                get
                {
                    return _tposm_takepicture2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TPOSM_TakePicture2 item info.
            /// </summary>
            [RepositoryItemInfo("9d377727-e82b-4903-a911-7f6ff5e55171")]
            public virtual RepoItemInfo TPOSM_TakePicture2Info
            {
                get
                {
                    return _tposm_takepicture2Info;
                }
            }

            /// <summary>
            /// The AvailabilityCheck item.
            /// </summary>
            [RepositoryItem("ae81bed6-f7dc-4004-9ccd-535a1280d341")]
            public virtual Ranorex.Container AvailabilityCheck
            {
                get
                {
                    return _availabilitycheckInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AvailabilityCheck item info.
            /// </summary>
            [RepositoryItemInfo("ae81bed6-f7dc-4004-9ccd-535a1280d341")]
            public virtual RepoItemInfo AvailabilityCheckInfo
            {
                get
                {
                    return _availabilitycheckInfo;
                }
            }

            /// <summary>
            /// The Validate_AVAILABILITYCHECKScreen item.
            /// </summary>
            [RepositoryItem("393237b7-ced8-4d87-8ebd-1210c7d416c1")]
            public virtual Ranorex.Text Validate_AVAILABILITYCHECKScreen
            {
                get
                {
                    return _validate_availabilitycheckscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate_AVAILABILITYCHECKScreen item info.
            /// </summary>
            [RepositoryItemInfo("393237b7-ced8-4d87-8ebd-1210c7d416c1")]
            public virtual RepoItemInfo Validate_AVAILABILITYCHECKScreenInfo
            {
                get
                {
                    return _validate_availabilitycheckscreenInfo;
                }
            }

            /// <summary>
            /// The AvailabilityCheck_List item.
            /// </summary>
            [RepositoryItem("f138f831-4b63-4831-9685-69a4e19b9778")]
            public virtual Ranorex.Container AvailabilityCheck_List
            {
                get
                {
                    return _availabilitycheck_listInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AvailabilityCheck_List item info.
            /// </summary>
            [RepositoryItemInfo("f138f831-4b63-4831-9685-69a4e19b9778")]
            public virtual RepoItemInfo AvailabilityCheck_ListInfo
            {
                get
                {
                    return _availabilitycheck_listInfo;
                }
            }

            /// <summary>
            /// The NonTKModules_List item.
            /// </summary>
            [RepositoryItem("bf4e6e3b-55f7-4e0b-a6db-e824a361af1f")]
            public virtual Ranorex.List NonTKModules_List
            {
                get
                {
                    return _nontkmodules_listInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The NonTKModules_List item info.
            /// </summary>
            [RepositoryItemInfo("bf4e6e3b-55f7-4e0b-a6db-e824a361af1f")]
            public virtual RepoItemInfo NonTKModules_ListInfo
            {
                get
                {
                    return _nontkmodules_listInfo;
                }
            }

            /// <summary>
            /// The List folder.
            /// </summary>
            [RepositoryFolder("6bab41d4-35f8-4a0c-90d5-eeaec9133a83")]
            public virtual PMISupervisorRepositoryFolders.ListFolder List
            {
                get { return _list; }
            }

            /// <summary>
            /// The List1 folder.
            /// </summary>
            [RepositoryFolder("29906d1f-ca78-45b5-a2c8-07b1367b1693")]
            public virtual PMISupervisorRepositoryFolders.List1Folder List1
            {
                get { return _list1; }
            }
        }

        /// <summary>
        /// The ListFolder folder.
        /// </summary>
        [RepositoryFolder("6bab41d4-35f8-4a0c-90d5-eeaec9133a83")]
        public partial class ListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _merchandiseronroute_radiobuttonInfo;
            RepoItemInfo _merchandiseramassignment_radiobuttonInfo;
            RepoItemInfo _merchandisertraining_radiobuttonInfo;
            RepoItemInfo _merchandiseronleave_radiobuttonInfo;
            RepoItemInfo _merchandiseroor_radiobuttonInfo;

            /// <summary>
            /// Creates a new List  folder.
            /// </summary>
            public ListFolder(RepoGenBaseFolder parentFolder) :
                    base("List", "form[@title='AttendenceListScreen']//list[@rid='list']", parentFolder, 30000, null, false, "6bab41d4-35f8-4a0c-90d5-eeaec9133a83", "")
            {
                _merchandiseronroute_radiobuttonInfo = new RepoItemInfo(this, "MerchandiserOnRoute_RadioButton", "?/?/radiobutton[@text='']", 30000, null, "a77f1d1f-3644-48e0-97c7-689d604229c0");
                _merchandiseramassignment_radiobuttonInfo = new RepoItemInfo(this, "MerchandiserAMAssignment_RadioButton", "container[3]/radiobutton[@text='']", 30000, null, "03692d8c-113e-43e0-853d-413292220071");
                _merchandisertraining_radiobuttonInfo = new RepoItemInfo(this, "MerchandiserTraining_RadioButton", "container[4]/radiobutton[@text='']", 30000, null, "2a260a3b-1c77-4506-8f5c-9053e56637d4");
                _merchandiseronleave_radiobuttonInfo = new RepoItemInfo(this, "MerchandiserOnLeave_RadioButton", "container[5]/radiobutton[@text='']", 30000, null, "b0cc18f0-c801-4bf9-adee-a9d000f0e657");
                _merchandiseroor_radiobuttonInfo = new RepoItemInfo(this, "MerchandiserOOR_RadioButton", "container[6]/radiobutton[@text='']", 30000, null, "9ce632ab-ed77-4aa4-a8cf-306bad058959");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6bab41d4-35f8-4a0c-90d5-eeaec9133a83")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6bab41d4-35f8-4a0c-90d5-eeaec9133a83")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MerchandiserOnRoute_RadioButton item.
            /// </summary>
            [RepositoryItem("a77f1d1f-3644-48e0-97c7-689d604229c0")]
            public virtual Ranorex.RadioButton MerchandiserOnRoute_RadioButton
            {
                get
                {
                    return _merchandiseronroute_radiobuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The MerchandiserOnRoute_RadioButton item info.
            /// </summary>
            [RepositoryItemInfo("a77f1d1f-3644-48e0-97c7-689d604229c0")]
            public virtual RepoItemInfo MerchandiserOnRoute_RadioButtonInfo
            {
                get
                {
                    return _merchandiseronroute_radiobuttonInfo;
                }
            }

            /// <summary>
            /// The MerchandiserAMAssignment_RadioButton item.
            /// </summary>
            [RepositoryItem("03692d8c-113e-43e0-853d-413292220071")]
            public virtual Ranorex.RadioButton MerchandiserAMAssignment_RadioButton
            {
                get
                {
                    return _merchandiseramassignment_radiobuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The MerchandiserAMAssignment_RadioButton item info.
            /// </summary>
            [RepositoryItemInfo("03692d8c-113e-43e0-853d-413292220071")]
            public virtual RepoItemInfo MerchandiserAMAssignment_RadioButtonInfo
            {
                get
                {
                    return _merchandiseramassignment_radiobuttonInfo;
                }
            }

            /// <summary>
            /// The MerchandiserTraining_RadioButton item.
            /// </summary>
            [RepositoryItem("2a260a3b-1c77-4506-8f5c-9053e56637d4")]
            public virtual Ranorex.RadioButton MerchandiserTraining_RadioButton
            {
                get
                {
                    return _merchandisertraining_radiobuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The MerchandiserTraining_RadioButton item info.
            /// </summary>
            [RepositoryItemInfo("2a260a3b-1c77-4506-8f5c-9053e56637d4")]
            public virtual RepoItemInfo MerchandiserTraining_RadioButtonInfo
            {
                get
                {
                    return _merchandisertraining_radiobuttonInfo;
                }
            }

            /// <summary>
            /// The MerchandiserOnLeave_RadioButton item.
            /// </summary>
            [RepositoryItem("b0cc18f0-c801-4bf9-adee-a9d000f0e657")]
            public virtual Ranorex.RadioButton MerchandiserOnLeave_RadioButton
            {
                get
                {
                    return _merchandiseronleave_radiobuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The MerchandiserOnLeave_RadioButton item info.
            /// </summary>
            [RepositoryItemInfo("b0cc18f0-c801-4bf9-adee-a9d000f0e657")]
            public virtual RepoItemInfo MerchandiserOnLeave_RadioButtonInfo
            {
                get
                {
                    return _merchandiseronleave_radiobuttonInfo;
                }
            }

            /// <summary>
            /// The MerchandiserOOR_RadioButton item.
            /// </summary>
            [RepositoryItem("9ce632ab-ed77-4aa4-a8cf-306bad058959")]
            public virtual Ranorex.RadioButton MerchandiserOOR_RadioButton
            {
                get
                {
                    return _merchandiseroor_radiobuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The MerchandiserOOR_RadioButton item info.
            /// </summary>
            [RepositoryItemInfo("9ce632ab-ed77-4aa4-a8cf-306bad058959")]
            public virtual RepoItemInfo MerchandiserOOR_RadioButtonInfo
            {
                get
                {
                    return _merchandiseroor_radiobuttonInfo;
                }
            }
        }

        /// <summary>
        /// The List1Folder folder.
        /// </summary>
        [RepositoryFolder("29906d1f-ca78-45b5-a2c8-07b1367b1693")]
        public partial class List1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _mondayInfo;
            RepoItemInfo _tuesdayInfo;
            RepoItemInfo _wednesdayInfo;
            RepoItemInfo _thursdayInfo;
            RepoItemInfo _fridayInfo;
            RepoItemInfo _saturdayInfo;

            /// <summary>
            /// Creates a new List1  folder.
            /// </summary>
            public List1Folder(RepoGenBaseFolder parentFolder) :
                    base("List1", "form[@title='RouteListScreen']//list[@rid='list']", parentFolder, 30000, null, false, "29906d1f-ca78-45b5-a2c8-07b1367b1693", "")
            {
                _mondayInfo = new RepoItemInfo(this, "Monday", "container[1]", 30000, null, "2e9836e4-c080-43f7-a10b-2a3eb3993c46");
                _tuesdayInfo = new RepoItemInfo(this, "Tuesday", "container[2]", 30000, null, "e47cea3d-afa5-497f-9810-c1411ea2633b");
                _wednesdayInfo = new RepoItemInfo(this, "Wednesday", "container[3]", 30000, null, "bc506f73-2bf3-4fcf-9f0a-e335794b0db4");
                _thursdayInfo = new RepoItemInfo(this, "Thursday", "container[4]", 30000, null, "3d58c29b-8946-4603-8a27-af462f71b341");
                _fridayInfo = new RepoItemInfo(this, "Friday", "container[5]", 30000, null, "e4ec867b-8e0d-4880-b8bb-cf71aaebae11");
                _saturdayInfo = new RepoItemInfo(this, "Saturday", "container[6]", 30000, null, "54e80a48-6c3d-4bdf-be67-7504ac3fcfe8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("29906d1f-ca78-45b5-a2c8-07b1367b1693")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("29906d1f-ca78-45b5-a2c8-07b1367b1693")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Monday item.
            /// </summary>
            [RepositoryItem("2e9836e4-c080-43f7-a10b-2a3eb3993c46")]
            public virtual Ranorex.Container Monday
            {
                get
                {
                    return _mondayInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Monday item info.
            /// </summary>
            [RepositoryItemInfo("2e9836e4-c080-43f7-a10b-2a3eb3993c46")]
            public virtual RepoItemInfo MondayInfo
            {
                get
                {
                    return _mondayInfo;
                }
            }

            /// <summary>
            /// The Tuesday item.
            /// </summary>
            [RepositoryItem("e47cea3d-afa5-497f-9810-c1411ea2633b")]
            public virtual Ranorex.Container Tuesday
            {
                get
                {
                    return _tuesdayInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Tuesday item info.
            /// </summary>
            [RepositoryItemInfo("e47cea3d-afa5-497f-9810-c1411ea2633b")]
            public virtual RepoItemInfo TuesdayInfo
            {
                get
                {
                    return _tuesdayInfo;
                }
            }

            /// <summary>
            /// The Wednesday item.
            /// </summary>
            [RepositoryItem("bc506f73-2bf3-4fcf-9f0a-e335794b0db4")]
            public virtual Ranorex.Container Wednesday
            {
                get
                {
                    return _wednesdayInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Wednesday item info.
            /// </summary>
            [RepositoryItemInfo("bc506f73-2bf3-4fcf-9f0a-e335794b0db4")]
            public virtual RepoItemInfo WednesdayInfo
            {
                get
                {
                    return _wednesdayInfo;
                }
            }

            /// <summary>
            /// The Thursday item.
            /// </summary>
            [RepositoryItem("3d58c29b-8946-4603-8a27-af462f71b341")]
            public virtual Ranorex.Container Thursday
            {
                get
                {
                    return _thursdayInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Thursday item info.
            /// </summary>
            [RepositoryItemInfo("3d58c29b-8946-4603-8a27-af462f71b341")]
            public virtual RepoItemInfo ThursdayInfo
            {
                get
                {
                    return _thursdayInfo;
                }
            }

            /// <summary>
            /// The Friday item.
            /// </summary>
            [RepositoryItem("e4ec867b-8e0d-4880-b8bb-cf71aaebae11")]
            public virtual Ranorex.Container Friday
            {
                get
                {
                    return _fridayInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Friday item info.
            /// </summary>
            [RepositoryItemInfo("e4ec867b-8e0d-4880-b8bb-cf71aaebae11")]
            public virtual RepoItemInfo FridayInfo
            {
                get
                {
                    return _fridayInfo;
                }
            }

            /// <summary>
            /// The Saturday item.
            /// </summary>
            [RepositoryItem("54e80a48-6c3d-4bdf-be67-7504ac3fcfe8")]
            public virtual Ranorex.Container Saturday
            {
                get
                {
                    return _saturdayInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Saturday item info.
            /// </summary>
            [RepositoryItemInfo("54e80a48-6c3d-4bdf-be67-7504ac3fcfe8")]
            public virtual RepoItemInfo SaturdayInfo
            {
                get
                {
                    return _saturdayInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}